Repository spryker/code-sniffer, pull requests merged in 2019-02, with the labels that each got.

#153 Better output for ClassFileNameSniff
  .travis.yml
  Spryker/Sniffs/Classes/ClassFileNameSniff.php
Labels: improvement

#158 TE-1634 Fix chainable error warning
  Spryker/Sniffs/Classes/ReturnTypeHintSniff.php
Labels: bug, prio

#157 GLUE-5470. Add glue specific constants rule.
  GlueStreamSpecific/Sniffs/Classes/AbstractStringInConstantOnlySniff.php
  GlueStreamSpecific/Sniffs/Classes/DependencyProviderStringInConstantOnlySniff.php
  GlueStreamSpecific/ruleset.xml
Labels: improvement, on-hold, request-review
