Repository spryker/code-sniffer, pull requests merged in 2019-11, with the labels that each got.

#202 Check all new Spryker* namespaces properly.
  Spryker/Sniffs/AbstractSniffs/AbstractSprykerSniff.php
  Spryker/Sniffs/Namespaces/SprykerNamespaceSniff.php
  Spryker/Sniffs/Namespaces/SprykerNoCrossNamespaceSniff.php
Labels: bug, prio, ready-for-release

#203 TE-4490: fixed license file finder
  Spryker/Sniffs/Commenting/FileDocBlockSniff.php
Labels: bug, merge-only, ready-for-release

#205 Allow empty .license files. Allow better core detection. Fix edge cases.
  README.md
  Spryker/Sniffs/AbstractSniffs/AbstractSprykerSniff.php
  Spryker/Sniffs/Commenting/AbstractFileDocBlockSniff.php
  Spryker/Sniffs/Commenting/FileDocBlockSniff.php
  Spryker/Sniffs/Commenting/SprykerAnnotationSniff.php
  Spryker/Sniffs/Commenting/SprykerConstantsSniff.php
  Spryker/Sniffs/Factory/NoPrivateMethodsSniff.php
  Spryker/Sniffs/Factory/OneNewPerMethodSniff.php
  Spryker/Sniffs/Namespaces/SprykerNoPyzSniff.php
  Spryker/Sniffs/WhiteSpace/NamespaceSpacingSniff.php
  docs/README.md
Labels: bug, ready-for-release
