Repository spryker/code-sniffer, pull requests merged in 2019-08, with the labels that each got.

#177 Added check that this is a function but not new operator
  Spryker/Sniffs/Namespaces/FunctionNamespaceSniff.php
Labels: bug, ready-for-release

#176 Added not equal sniff
  Spryker/Sniffs/PHP/NotEqualSniff.php
  docs/README.md
Labels: improvement

#178 Bugfix/variable null type last
  Spryker/Sniffs/Commenting/DocBlockVariableNullHintLastSniff.php
Labels: ready-for-release

#179 Fix method spacing, beginning newline with PHP71 return typehinting.
  Spryker/Sniffs/WhiteSpace/MethodSpacingSniff.php
Labels: bug, ready-for-release
