Repository spryker/code-sniffer, pull requests merged in 2020-02, with the labels that each got.

#209 Activate PSR 12 ruleset.
  Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
  Spryker/Sniffs/Commenting/DocBlockApiAnnotationSniff.php
  Spryker/Sniffs/ControlStructures/ConditionalExpressionOrderSniff.php
  Spryker/Sniffs/Formatting/ArrayDeclarationSniff.php
  Spryker/Sniffs/WhiteSpace/EmptyLinesSniff.php
  Spryker/Sniffs/WhiteSpace/OperatorSpacingSniff.php
  Spryker/ruleset.xml
Labels: improvement, ready-for-release

#210 TE-4648 Slevomat6
  .travis.yml
  Spryker/Sniffs/AbstractSniffs/AbstractSprykerSniff.php
  Spryker/Sniffs/Classes/MethodArgumentDefaultValueSniff.php
  Spryker/Sniffs/Classes/MethodDeclarationSniff.php
  Spryker/Sniffs/Commenting/DocBlockInheritSniff.php
  Spryker/Sniffs/Commenting/DocBlockParamAllowDefaultValueSniff.php
  Spryker/Sniffs/Commenting/DocBlockParamSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnNullableTypeSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnVoidSniff.php
  Spryker/Sniffs/Commenting/DocBlockSniff.php
  Spryker/Sniffs/Commenting/DocBlockTagGroupingSniff.php
  Spryker/Sniffs/Commenting/DocBlockTagOrderSniff.php
  Spryker/Sniffs/Commenting/DocBlockTypeOrderSniff.php
  Spryker/Sniffs/Commenting/DocBlockVariableNullHintLastSniff.php
  Spryker/Sniffs/Commenting/FullyQualifiedClassNameInDocBlockSniff.php
  Spryker/Sniffs/Commenting/SprykerAnnotationSniff.php
  Spryker/Sniffs/Commenting/SprykerBridgeSniff.php
  Spryker/Sniffs/ControlStructures/NoInlineAssignmentSniff.php
  Spryker/Sniffs/Formatting/ArrayDeclarationSniff.php
  Spryker/ruleset.xml
  SprykerStrict/Sniffs/TypeHints/ParameterTypeHintSniff.php
  SprykerStrict/Sniffs/TypeHints/PropertyTypeHintSniff.php
  SprykerStrict/ruleset.xml
  bin/tokenize.php
  composer.json
  docs/README.md
Labels: improvement, prio, ready-for-release

#212 Feature/te-4665: add sniffer method signature parameters line break
  Spryker/Sniffs/AbstractSniffs/AbstractSprykerSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnNullableTypeSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnSelfSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnVoidSniff.php
  Spryker/Sniffs/Commenting/DocBlockTestGroupAnnotation2Sniff.php
  Spryker/Sniffs/Commenting/DocBlockTestGroupAnnotationSniff.php
  Spryker/Sniffs/Commenting/DocBlockThrowsSniff.php
  Spryker/Sniffs/Commenting/DocBlockVarSniff.php
  Spryker/Sniffs/Commenting/DocBlockVariableNullHintLastSniff.php
  Spryker/Sniffs/Commenting/FullyQualifiedClassNameInDocBlockSniff.php
  Spryker/Sniffs/Commenting/SprykerAnnotationSniff.php
  Spryker/Sniffs/ControlStructures/NoInlineAssignmentSniff.php
  Spryker/Sniffs/Formatting/MethodSignatureParametersLineBreakMethodSniff.php
  Spryker/Sniffs/PHP/PreferCastOverFunctionSniff.php
  Spryker/Sniffs/Testing/MockSniff.php
  composer.json
  docs/README.md
  tests/Spryker/Sniffs/Formatting/MethodSignatureParametersLineBreakMethodSniffTest.php
  tests/TestCase.php
  tests/_data/MethodSignatureParametersLineBreakMethod/after.php
  tests/_data/MethodSignatureParametersLineBreakMethod/before.php
Labels: improvement

#184 Notify about not using deprecated functions.
  Spryker/ruleset.xml
Labels: prio
