Repository spryker/code-sniffer, pull requests merged in 2021-02, with the labels that each got.

#246 Removed disallowed is_resource check.
  Spryker/Sniffs/PHP/DisallowFunctionsSniff.php
Labels: bug

#247 TE-8545: Fix double typo exception in Specification tag
  Spryker/Sniffs/Commenting/DocBlockApiAnnotationSniff.php
Labels: merge-only, ready-for-release

#242 Visibility for final methods.
  Spryker/Sniffs/Classes/MethodDeclarationSniff.php
Labels: improvement, merge-only, ready-for-release
