Repository spryker/code-sniffer, pull requests merged in 2022-04, with the labels that each got.

#319 Fix newline issue on constants.
  Spryker/ruleset.xml
Labels: improvement

#315 TE-10552 Using generics for all collections including all objects
  Spryker/Sniffs/Commenting/DisallowArrayTypeHintSyntaxSniff.php
  Spryker/Sniffs/Commenting/TypeHintSniff.php
  tests/Spryker/Sniffs/Commenting/DisallowArrayTypeHintSyntaxSniffTest.php
  tests/Spryker/Sniffs/Commenting/TypeHintSniffTest.php
  tests/_data/DisallowArrayTypeHintSyntax/after.php
  tests/_data/DisallowArrayTypeHintSyntax/before.php
  tests/_data/TypeHint/after.php
  tests/_data/TypeHint/before.php
Labels: ready-for-release, merge-only

#322 Fix method annotation sniff when using final classes
  Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
Labels: bug

#320 Improve method annotation sniff
  README.md
  Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/ConfigMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/EntityManagerMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/FacadeMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/FactoryMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/QueryContainerMethodAnnotationSniff.php
  Spryker/Sniffs/MethodAnnotation/RepositoryMethodAnnotationSniff.php
Labels: improvement

#325 Fix path detection for nonsplit
  Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
Labels: bug, prio, merge-only
