Repository spryker/code-sniffer, pull requests merged in 2022-09, with the labels that each got.

#357 Add missing elseif case.
  Spryker/Sniffs/ControlStructures/ElseIfDeclarationSniff.php
  Spryker/ruleset.xml
  docs/README.md
Labels: bug, ready-for-release

#359 FRW-332 Fix up PHPStan and typeless param.
  Spryker/Sniffs/Commenting/DocBlockConstSniff.php
  Spryker/Sniffs/Commenting/DocBlockParamAllowDefaultValueSniff.php
  Spryker/Sniffs/Commenting/DocBlockParamArraySniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnNullSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnNullableTypeSniff.php
  Spryker/Sniffs/Commenting/DocBlockReturnTagSniff.php
  Spryker/Sniffs/Commenting/FullyQualifiedClassNameInDocBlockSniff.php
  Spryker/Sniffs/Commenting/TypeHintSniff.php
Labels: bug, prio, merge-only

#360 FRW-332 Change min PHP version to 7.4
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: merge-only

#361 PHP 82 check
  .github/workflows/ci.yml
Labels: merge-only
